debug: ${EVERNOTEBOT_DEBUG}:true
default_mode: multiple_notes
host: ${EVERNOTEBOT_HOSTNAME}
tmp_root: /tmp/
oauth_callback: https://${EVERNOTEBOT_HOSTNAME}/evernote/oauth
telegram:
    bot_name: evernotebot
    token: ${TELEGRAM_API_TOKEN}
evernote:
    access:
        basic:
            key: ${EVERNOTE_BASIC_ACCESS_KEY}
            secret: ${EVERNOTE_BASIC_ACCESS_SECRET}
        full:
            key: ${EVERNOTE_FULL_ACCESS_KEY}
            secret: ${EVERNOTE_FULL_ACCESS_SECRET}
storage:
    users:
        class: evernotebot.bot.storage.Sqlite
        dirpath: /tmp/evernotebot-data/
        db_name: evernotebot
        collection: users
    failed_updates:
        class: evernotebot.bot.storage.Sqlite
        dirpath: /tmp/evernotebot-data/
        db_name: evernotebot
        collection: failed_updates
